import { Inter } from "next/font/google";
import styles from "./page.module.sass"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={styles.html} lang="en">
      <body className={styles.body} style={{margin: '0px', width: "100vw", height: "100vh", backgroundColor: "#dddddd" }}>{children}</body>
    </html>
  );
}
